### ISSUE TITLE
SharedDeserializeMap is not Send

### ISSUE THREAD

**Issue by Kixiron** [rkyv/rkyv#174]
`SharedDeserializeMap` is not `Send` because of the `*const u8` pointers it contains

**Comment by djkoloski** [comment]
I think this will also require adding `SharedPointer: Send` or else it may not be safe to send the map across threads.

**Comment by djkoloski** [comment]
Hmm, so this one's a bit of a head-scratcher. Requiring `SharedPointer: Send` makes it so that `Rc<T>` cannot implement `SharedPointer`. I could define a `SendableSharedPointer` that is only implemented for `Arc<T>` and split the implementation of `SharedDeserializeMap` for sendable and unsendable shared pointers. Would that be alright for fixing your issue?

**Comment by Kixiron** [comment]
Either way sounds valid to me, I ended up not actually needing shared deserialization

**Comment by djkoloski** [comment]
I’ll leave this one on the backburner until someone needs this then. Give it some time to mature and maybe there’s another way of approaching the problem that makes more sense.

**Comment by djkoloski** [comment]
Closing this issue since the feature ended up not being needed.
