### ISSUE TITLE
Validation tests failing on Apple M1

### ISSUE THREAD

**Issue by b8591340** [rkyv/rkyv#197]
```rust
test validation::test_alloc::tests::basic_functionality ... FAILED

failures:

---- validation::test_alloc::tests::basic_functionality stdout ----
thread 'validation::test_alloc::tests::basic_functionality' panicked at 'called `Result::unwrap()`
on an `Err` value: ContextError(ArchiveError(Unaligned { ptr: 0x16b97e316, align: 4 }))’,
rkyv_test/src/validation/test_alloc.rs:128:16
```

I didn’t investigate further but do let me know if I can help.

**Comment by djkoloski** [comment]
I'll get these tested on an M1 machine and see if I can track down the issue.

**Comment by djkoloski** [comment]
Could you run the following snippet? Just want to sanity-check primitive alignment for M1.

```rust
use core::mem::align_of;

fn main() {
    println!("u8: {}", align_of::<u8>());
    println!("u16: {}", align_of::<u16>());
    println!("u32: {}", align_of::<u32>());
    println!("u64: {}", align_of::<u64>());
    println!("u128: {}", align_of::<u128>());
    println!("i8: {}", align_of::<i8>());
    println!("i16: {}", align_of::<i16>());
    println!("i32: {}", align_of::<i32>());
    println!("i64: {}", align_of::<i64>());
    println!("i128: {}", align_of::<i128>());
    println!("f32: {}", align_of::<f32>());
    println!("f64: {}", align_of::<f64>());
    println!("char: {}", align_of::<char>());
    println!("bool: {}", align_of::<bool>());
}
```

The error in question says that an alignment of 4 was expected but it found an alignment of 2. The only way this should be able to happen is if `align_of::<u16>() = 4`, which is unlikely but not impossible.

**Comment by djkoloski** [comment]
Alright, I think this might be a bit of a confusing one. You may have been testing like `cargo test --features "validation size_16"`, but that leaves the default features enabled. One of the default features is `size_32`, which means that both `size_16` and `size_32` were enabled for that test. This should be a compiler error since the features are mutually exclusive, but due to the way the code is structured it ended up just shadowing a few variables. Because having both features enabled is an error, I have added additional compiler errors in 9a5552b132a3acf452db5a645689f6ab2d0d9e5d. I'm not sure that this is the issue that you ran into, but if it is could you try re-running the tests with the latest commit?

**Comment by b8591340** [comment]
```rust
u8: 1
u16: 2
u32: 4
u64: 8
u128: 16
i8: 1
i16: 2
i32: 4
i64: 8
i128: 16
f32: 4
f64: 8
char: 4
bool: 1
```

Seem standard? Looking through bash history the tests were all run with `--no-default-features` as I just copied them from the release_checklist to get started; so no luck.

**Comment by djkoloski** [comment]
Yep, all those look pretty normal. One potentially interesting point is that the 128-bit integer type is 16-byte aligned, whereas on most x64 machines it is only 8-byte aligned. I'll file an issue about this, as this may require that rkyv put 128-bit support behind a feature or wrap the 128-bit types in a more strictly aligning newtype. I'm still trying to get access to an M1 to run those tests, I'll update when I get a successful repro and dig in.

**Comment by djkoloski** [comment]
I got my hands on a machine to run the tests. It is a Mac mini with an Apple M1 chip in it. I ran the release test suite and it looks like everything passed. I ran everything except the wasm-pack tests, since those should be wasm and platform-agnostic. The machine also gave the same results for the alignment tests. So I don't seem to be able to reproduce the error in question. Could you try to get a repro again and see if you are able to?

**Comment by b8591340** [comment]
It was indeed like you suggested! But interestingly it was due to running `cargo test --no-default-features --features "size_16 std validation”` in the workspace root rather than in `rkyv_test`.

It’s due to `rkyv_bench`, `rkyv_dyn(_test)?`, `rkyv_json_example`, and `opcode` pulling in `rkyv` with default features enabled despite `--no-default-features`. I’ve attempted to set `resolver = 2"` at the workspace-level (see [here](https://doc.rust-lang.org/cargo/reference/features.html#resolver-version-2-command-line-flags)), but it still doesn’t disable the features; don’t know if it’s expected behavior. 

With the workspace root as `cwd` 
```
cargo test -p rkyv_test -p rkyv_dyn --no-default-features --features "size_16 std validation”
```
used to fail `basic_validation` and now errors at 9a5552b132a3acf452db5a645689f6ab2d0d9e5d, while 
```
cargo test -p rkyv_test --no-default-features --features "size_16 std validation”
```
works as if we were in `rkyv_test`.

**Comment by djkoloski** [comment]
Ohhhh that makes sense. Sounds like we got bit by the resolver like you deduced. I'll file an issue to change the resolver over, though I think it will be a breaking change and require a major version bump. Thanks for the help and sticking it out!

**Comment by b8591340** [comment]
Sorry, I wasn’t clear: switching to the new resolver does _not_ solve the issue. As I was attempting to figure it out here in writing I fixed it, see #200.

**Comment by djkoloski** [comment]
There are a few other reasons to switch resolvers, most notably from https://github.com/bitshifter/glam-rs/pull/223, so it's not just from this thread.

**Comment by b8591340** [comment]
Of course!
