### ISSUE TITLE
`#[derive(Archive)]` with `#[repr(packed)]` needs to conform to `unaligned_references`

### ISSUE THREAD

**Issue by b8591340** [rkyv/rkyv#198]
The traditional behavior is UB and will become an error as per https://github.com/rust-lang/rust/issues/82523.

**Comment by djkoloski** [comment]
I'll take a look at this as soon as possible. Did you encounter this during a particular action (e.g. testing with the 2021 edition)?

**Comment by b8591340** [comment]
Nightly!

I wonder, what does `copy` apply to? Copyable non-`repr(packed)` struct without padding? Or does it also apply to `repr(packed)`?

Furthermore does `copy` automatically apply to unpadded copyable types or is `#[copy_safe]` required? 

And does a `repr(packed)` struct need either feature `copy` or `#[copy_safe]` in order to benefit from copy optimizations or is it inferred at codegen by the combination of `#[derive(Archive)]` and `#[repr(packed)]`?

**Comment by djkoloski** [comment]
I'll do my best to clarify, but please let me know if I miss anything.

During serialization, some simple structs may be trivially serializable by copying them directly (byte for byte) to the output. A good example would be a point (some `f32`s), or some raw data (think of a collection of primitive data fields). Copy optimizations in rkyv allow some containers to skip calling serialize on all their elements and directly copy them to the output, but only if the element type implements `ArchiveCopy`. `ArchiveCopy` is an auto trait (unstable), so users don't have to do any work here. An important note is that although copy optimization _permits_ this behavior, it is not required and the normal serialization implementation may be called anyway.

There's one more thing that needs to be considered though. If a struct has padding bytes, those bytes will not be initialized and may change from run to run. This can break deterministic serialization or, in the absolute worst case, could leak previously-initialized and sensitive memory. To avoid accidentally causing this, there's an additional trait `ArchiveCopySafe` that marks a type as safe to copy optimize. In practice, this trait just means "this type has no padding bytes".

Sometimes though, you don't care about determinism or leaking memory and just want maximum performance. In these cases, you can enable the `copy_unsafe` feature. This will copy optimize all types that implement `ArchiveCopy` and not just ones that implement both `ArchiveCopy` and `ArchiveCopySafe`.

Alright, with that out of the way I can address your questions more directly. Since `repr(packed)` types have alignment 1 and no intra-struct padding, they are always safe to copy optimize. However, `repr(packed)` is not entirely safe to use with derived `Archive` and implementations because the safety contract implicitly requires that the destination pointer is properly aligned. This is an area where more discussion would be great for figuring out what features users need to work with packed types.

**Comment by b8591340** [comment]
> There's one more thing that needs to be considered though. If a struct has padding bytes, those bytes will not be initialized and may change from run to run. This can break deterministic serialization or, in the absolute worst case, could leak previously-initialized and sensitive memory. To avoid accidentally causing this, there's an additional trait ArchiveCopySafe that marks a type as safe to copy optimize. In practice, this trait just means "this type has no padding bytes”.

With “may change from run to run” are you referring to the lack of a stable layout/ABI for `repr(rust)`? If so, would `#[repr(C)]` `#[derive(Archive)]` `#[copy_safe]` sidestep the safety issues around padding?

With regard to packing: a safe derive could implement accessor methods that do `read_unaligned` internally when the pointer is unaligned. I haven’t had a chance to read up on what Rust itself plans to do on this front; having to do `addr_of!`, `read_unaligned`, and `write_unaligned` for every field read/write is most certainly impractical.

**Comment by djkoloski** [comment]
By "may change from run to run" I just mean that the padding bytes (written to the output) may change from run to run. This breaks reproducibility, which may or may not be a problem for your use case. `#[repr(C)]` will still have that problem, since it will still have padding. It's up to you to decide whether reproducibility is a problem.

WRT packing, I think could be possible by reworking the `Archive` trait to support writing unaligned types. This would be a pretty big feature though, so I would encourage some more details about your use case and how you'd like to use `repr(packed)` with rkyv. 🙂 If you get some thoughts together, feel free to [drop in the discord](https://discord.gg/65F6MdnbQh) or file an issue and we can work from there.

**Comment by djkoloski** [comment]
This issue is stale with respect to 0.8 development for a few reasons:

- rkyv officially doesn't support `repr(packed)` types
- The soundness issues mentioned here have been fixed
- The new `aligned`/`unaligned` features provide the same outcomes as `repr(packed)`

With that in mind, I'm going to close this as obsolete

**Comment by djkoloski** [comment]
This issue is pretty stale with respect to 0.8 development:

1. Technical decision: rkyv doesn't support `repr(packed)`
2. Padding is now guaranteed to be zeroed
3. The new `aligned`/`unaligned` features provide the same benefit as `repr(packed)` support

With those in mind, I'm going to close this issue.
