### ISSUE TITLE
(too low?) Size limit when serializing to ArchivedBTreeMap<u16, ArchivedBTreeMap<String, ArchivedCustomObject>>

### ISSUE THREAD

**Issue by zertyz** [rkyv/rkyv#236]
Hi, David.

First, thanks for the wonderful lib.

Is there a 2G limit when generating Archives? I'm on a x86_64 Linux...

When archiving & saving, the program panicked with:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExceedsStorageRange', /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.28/src/rel_ptr/mod.rs:300:42

The resulting (partial, I presume) file is ~2G:
-rw-r--r-- 1 luiz users 2167734108 Dec 30 13:38 trades.rkyv

If this is a bug, please tell me how can I be of help to spot it.

Thanks,
Luiz.

**Comment by djkoloski** [comment]
Hi Luiz, thanks for filing an issue. This error is raised during relative pointer construction, and occurs when a relative pointer has to point farther than it can represent. This usually happens around 2 GB because that's the maximum range for an `i32` (2,147,483,647), and `i32` is the offset type by default. You can disable the `size_32` feature and enable the `size_64` feature to use `i64` instead, which will allow your files to be much larger. Note that data serialized with different `size_*` features will not be compatible with each other, so you'll need to re-serialize your data with `size_64`.

Here's how you can change your default size type in your `Cargo.toml`:

```toml
[dependencies]
rkyv = { version = "0.7", default-features = false, features = ["size_64", "std"] }
```

**Comment by zertyz** [comment]
Thank you so much.
Worked wonderfully.

Best wishes,
Luiz.
