### ISSUE TITLE
How to integrate Archive/Serialize/Deserialize into a library trait?

### ISSUE THREAD

**Issue by djahandarie** [rkyv/rkyv#266]
I'm trying to add rkyv support to [openraft](https://github.com/datafuselabs/openraft), and for the most part it is smooth (just adding the Archive,Serialize,Deserialize derives on relevant types behind a feature flag).

However, I'm running into an issue with this *trait*: 

https://github.com/datafuselabs/openraft/blob/21959ffce1a451b7888ffcfc9931402b58fe7d6f/openraft/src/node.rs#L17-L35

which gets used in very many places that need to be serializeable, for example:

https://github.com/datafuselabs/openraft/blob/21959ffce1a451b7888ffcfc9931402b58fe7d6f/openraft/src/vote/leader_id.rs#L16-L24

It seems quite difficult to just add `rkyv::Archive + rkyv::Serialize<S> + rkyv::Deserialize<T, D>` to the list of inherited traits in `node.rs`, because then `NodeId` needs to have `<S,T,D>` parameters on it, which will further infect every single parent type. Which is not great if I want to put this behind a feature flag. Plus I don't know how I'd enforce the right traits on the associated `Archive` type (`Debug`, `PartialEq` etc).

I assume I'm just not understanding how to properly do this, so any guidance would be welcome. (Sorry, very beginner user of the rkyv, I only really understand how to use the derive interface for it.)

**Comment by djkoloski** [comment]
I can take a look manually, but I think that in this case it should be sufficient to just omit the `Archive + Serialize + Deserialize` bounds from the trait and bound them when you need them. For example, if you had some `serialize_node<N>` method, you would add `S` and `D` parameters (so that the caller can decide how to serialize/deserialize) and bound `N: Archive + Serialize<S>, N::Archived: Deserialize<N, D>`.

I think this sounds super cool, and I'd encourage you to swing by [the discord](https://discord.gg/65F6MdnbQh) if some synchronous communication would help.

**Comment by djkoloski** [comment]
Closing, feel free to reopen or get in touch through the discord. 🙂
