### ISSUE TITLE
Q: how to correctly apply repr attr for backward compat?

### ISSUE THREAD

**Issue by kwonoj** [rkyv/rkyv#291]
I feel bit lost and probably this is very dumb q, please bear with me if that's the case.

After suggestion from https://github.com/rkyv/rkyv/issues/164#issuecomment-1059802975, I tried to apply this practices for the codebase I'm working. It causes some unexpected runtime error _only on certain machines_ (so far I observed aarch64 appl silicon - notably M1 mac), while other machines working properly like local Windows machine / Linux based CI machines.

The symptoms are when guest try to deserialize given struct, its runtime throws like below:

```
sers/ojkwon/github/swc-coverage-instrument/target/wasm32-wasi/debug/swc_plugin_coverage.wasm

Caused by:
    0: RuntimeError: out of bounds memory access
    1: heap_get_oob
```

Sadly, no more detailed stacks / whereabout where it exactly try to do.

Couple of bisecting leads me specific change (https://github.com/swc-project/swc/pull/5062/files) caused this. More specifically, adding `archive_attr(repr(C | u32), derive(bytecheck::CheckBytes))` makes this happen.

I'm not sure where to dig further / and what to specifically fix at this point and bit stuck. Is there any incorrect practices I did in the offending PR can cause machine-specific runtime error? if that's the case, what's the recommended way to fix it?

Sorry question is bit blur to not able to include suffecient detail. These are only I got so far.

**Comment by djkoloski** [comment]
Hey, sorry for the long delay in responding. I'd like to dive deeper into this to understand what's going on better. How can I test to get the same error as described in the issue? If I could pull something down and `cargo test` that would be ideal, but any repro would work. I also noticed that the example given is running in wasm; does this repro on a host I could debug like an M1 mac? I have hardware to test on M1, I just want to be able to attach a debugger and root around.

Linking https://github.com/rkyv/rkyv/issues/288 since it's also related to swc. I'd like to get this resolved soon.

**Comment by kwonoj** [comment]
Hi, I'd like to present some simple isolation, but so far failed. Given swc is somewhat large codebase and involves two different binaries (for the host runtime, and the plugin to exchange binary) it may not be easy to do single `cargo test` right away. 

I'm trying to create some set of features to create a specific host & binary test against to see if it can reproduce issues.

**Comment by djkoloski** [comment]
Merging this issue into #288
