### ISSUE TITLE
Convention for deriving Archive for Copy types in the ecosystem?

### ISSUE THREAD

**Issue by yongqli** [rkyv/rkyv#292]
Hi,

I'm currently trying to improve `rkyv` support within `chrono` -- you can see my pull request here: https://github.com/chronotope/chrono/pull/762

With `Copy` types it would be convenient to use `Self` as the `Archived` type so that all the traits and methods carry over. However, this does not work if `rkyv` was configured to use a specific endianness. I was wondering whether you have any thoughts or recommendations on how other projects can add support for `rkyv` while maintaining compatibility throughout the ecosystem.

**Comment by djkoloski** [comment]
In the linked PR, I don't think you should have `archive_be` and `archive_le` features for chrono. These features should be chosen by whatever the final binary is by enabling those features in rkyv, and that choice should propagate through all of the libraries that support rkyv.

I'm not sure how to support this kind of conditional attribute you'd like to add. The only way that comes to mind is to move the conditional into the argument for rkyv (i.e. `#[archive_cfg(not(any(feature = "archive_le", feature = "archive_be"), as = "Self")]`). This seems like a reasonable way to address this specific issue.

Having separate archived and unarchived types is currently a pain point that is difficult to address. My goal for the next major revision is to address this by adding more functionality to archived types so that you can use them for everything, instead of having to deserialize to the native type and use that.

**Comment by yongqli** [comment]
Yeah that sounds like it would work. Support for `archive_cfg` will have to be added to `rkyv` itself, correct?

**Comment by djkoloski** [comment]
Yes, this would require adding a new feature to rkyv's derive macro. Because this is additive, we should be able to release it in a bugfix (minor) point release. Would you be interested in helping out with this work?

**Comment by djkoloski** [comment]
I've made some decisions on technical direction for the future of rkyv which impact this issue:

1. Archived types must now implement `Portable`, so we can't get around using rend's primitive types
2. Developers should not care whether rkyv uses little-endian or big-endian types by default, and so rkyv won't do more than export the choices it made for archived primitives
3. "Archived types everywhere" has turned out to be too much work and complexity for me. I think it's still possible, but it's not a place where I can responsibly invest my time or effort.

I think the opportunity for archived-self types is pretty limited and requires a significant amount of legwork to cover all possible bases. With those in mind, I'm going to close this issue and say that if you want to support rkyv you'll have to provide a separate archived type in most cases.

**Comment by tv42** [comment]
For anyone else who ended here from a search, see https://github.com/rkyv/rkyv/issues/167
