### ISSUE TITLE
Is it possible to proxy &ArchivedT to &T without copy?

### ISSUE THREAD

**Issue by cpunkzzz** [rkyv/rkyv#312]
I'm sure there is a reason why it's not supported, but I'm curious if there is way?

**Comment by cpunkzzz** [comment]
@djkoloski maybe you know?

**Comment by djkoloski** [comment]
Sorry for the delay. If you're willing to put in the work, you could put your methods in a trait and parameterize everything over that (e.g. impl `MyTypeTrait` for `&T` and `&ArchivedT` then make all your structs/functions take `T: MyTypeTrait`). In general there's not an easy way to do this because although the code you write for the archived and unarchived versions may be _textually_ the same, it's usually not interpreted the same way. For simple (POD) types you can also use `#[archive(as = "T)]` to avoid generating a separate archived type, which gives the same effect.

**Comment by cpunkzzz** [comment]
@djkoloski Thanks for the answer! What I'm trying to do is reuse code that was written for &T with the archived version, so it won't compile when I try to pass in the archived version. Is there even something unsafe to do that will make the compiler understand that it's the same type?

**Comment by djkoloski** [comment]
`T` and `ArchivedT` are different types by default. Are you writing your own impls?

**Comment by cpunkzzz** [comment]
I meant that I'm trying to use an external library that expects type &T as a parameter. I'm reusing that code from a constrained environment where deserialization is very expensive so that's why I'm using rkyv. I could rewrite the library functions to take ArchiveT, but I wanted to see if it's possible to avoid

**Comment by djkoloski** [comment]
In general, no, you get an `&T` from an `&ArchivedT` without deserializing.

**Comment by cpunkzzz** [comment]
Make sense, thanks!
