### ISSUE TITLE
Tuple of references doesn't impl rkyv::Serialize

### ISSUE THREAD

**Issue by namse** [rkyv/rkyv#335]
I tried to pass some references with tuple to function to serialize them to compare at next time. 
The reason why I uses references is because I don't want to pass the ownership of data. And the usage of tuple is for anonymous type.

But the tuple of references seems not impl rkyv::Serialize.

```rust
fn main() {
    let f: f32 = 5.5;
    let i: i32 = 1;
    use_effect(|| {}, (&i, &f)); // << error 
}

fn use_effect(
    callback: impl FnOnce(),
    dependency: impl rkyv::Serialize<rkyv::ser::serializers::AllocSerializer<64>>,
) {
    let a = rkyv::to_bytes(&dependency);
    todo!()
}
```

compile error is like below,
```
the trait bound `&i32: Serialize<CompositeSerializer<AlignedSerializer<AlignedVec>, FallbackScratch<HeapScratch<64>, AllocScratch>, SharedSerializeMap>>` is not satisfied
the following other types implement trait `Serialize<S>`
```

Is it intented? If so, would there be a good way to pass multiple, different types as parameter to serialize in function, without passing ownership to function?

**Comment by namse** [comment]
For information, No compile error with bincode 2.0.0-rc.2

```rust

fn main() {
    let f: f32 = 5.5;
    let i: i32 = 1;
    use_effect(|| {}, (&i, &f)); // << compile error
    use_effect2(|| {}, (&i, &f)); // but no compile error with bincode 2.0.0-rc.2
}

fn use_effect(
    callback: impl FnOnce(),
    dependency: impl rkyv::Serialize<rkyv::ser::serializers::AllocSerializer<64>>,
) {
    let a = rkyv::to_bytes(&dependency);
    todo!()
}
fn use_effect2(callback: impl FnOnce(), dependency: impl bincode::enc::Encode) {
    let a = bincode::encode_to_vec(&dependency, bincode::config::standard());
    todo!()
}
```

**Comment by djkoloski** [comment]
Yes, this is intended. If you are trying to serialize a struct that has references in its fields, you can use wrapper types to specify the behavior you want. See:

- https://docs.rs/rkyv/latest/rkyv/with/struct.Inline.html
- https://docs.rs/rkyv/latest/rkyv/with/struct.RefAsBox.html

rkyv does this because it does its best to preserve the exact same semantics as the serialized value by default. For references, there is no way to have the same semantics after serialization; you have to specify that you want to copy the value in some way.
