### ISSUE TITLE
Misalignmet crash for `HashSet` on rust 1.70.0-beta.1 and 1.71.0-nightly on macOS

### ISSUE THREAD

**Issue by mikkeldenker** [rkyv/rkyv#382]
The following code seems to crash on the latest non-stable versions of rust using `rkyv="0.7.41"` on an m1 mac.

```rust
use std::collections::HashSet;

fn main() {
    let mut set = HashSet::new();
    set.insert(1);

    let bytes = rkyv::to_bytes::<HashSet<u64>, 256>(&set).unwrap();
    dbg!(&bytes);

    let crashing_bytes: [u8; 28] = [
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 236, 255, 255, 255, 240, 255,
        255, 255,
    ];

    assert_eq!(&bytes[..], &crashing_bytes[..]);

    // let crashing_bytes = crashing_bytes.to_vec();
    let archived = unsafe { rkyv::archived_root::<HashSet<u64>>(&crashing_bytes) };
    assert_eq!(*archived.iter().next().unwrap(), 1);
}
```

It generates the error `misaligned pointer dereference: address must be a multiple of 0x8 but is 0x16bbea0f4` but the code seems to work on the latest rust stable and also if we allocate the bytes into a vec before deserializing (i.e. un-commenting the line `let crashing_bytes = crashing_bytes.to_vec();`).

The program crashes on my m1 mac but seems to work on linux.

**Comment by djkoloski** [comment]
This looks like a pretty straightforward alignment issue. `Vec` does not guarantee that its elements are more highly-aligned than they have to be. So the `Vec<u8>` in your example may even only have an alignment of 1. This matters for rkyv because (depending on the buffer contents) the alignment must be higher. An alignment of 4-16 is usually required, which you can get with rkyv's `AlignedVec` container. This alignment invariant is a safety condition of `archived_root` and is checked by `check_archived_root`.

**Comment by mikkeldenker** [comment]
Aaaah yes, turns out I had a completely wrong understanding of how the alignment of subslices worked. The code I provided apparently had nothing to do with my underlying issue. Sorry for the inconvenience, but thanks for pointing me in the right direction.

Closing this as the problem had nothing to do with rkyv.
