### ISSUE TITLE
Expected _ Found With<_, _>

### ISSUE THREAD

**Issue by billyb2** [rkyv/rkyv#398]
I'm not really sure what the issue is, but I can't deserialize a struct that I have back to it's original type. The struct looks like this:

```rust
#[derive(Serialize, Debug, Deserialize, Archive)]
#[archive(check_bytes)]
pub enum GameMsgResp {
    LobbyNotReady,
    LobbyFull,
    NotInLobby,
    State(GameState),
}

```

And I have an enum that I want to check in that struct, with the following code:
```rust
let archive = rkyv::archived_root::<GameMsgResp>(&buffer).unwrap();

if let ArchivedGameMsgResp::State(state) = archive {
    let state: GameState = state.deserialize(&mut rkyv::Infallible).unwrap();
    game_state = Some(state);
}
```

However, when I try to compile this code, I get the following error:
```
error[E0308]: mismatched types
   --> src/main.rs:114:40
    |
114 |                 let state: GameState = state.deserialize(&mut rkyv::Infallible).unwrap();
    |                            ---------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `GameState`, found `With<_, _>`
    |                            |
    |                            expected due to this
    |
    = note: expected struct `GameState`
               found struct `With<_, _>`
```

I don't understand why I'm getting the With struct, or how to deserialize back to the original enum.

**Comment by djkoloski** [comment]
This is unfortunately just a bad compiler diagnostic. It _should_ say that the bound `ArchivedGameState: Deserialize<GameState, Infallible>` is not satisfied, but instead it points to a blanket impl and says that impl doesn't match.

The problem here is almost certainly that the bound is unfulfilled. If you use UFCS, it may coax the compiler into giving you a more helpful error:

```rust
let state = <ArchivedGameState as Deserialize<GameState, Infallible>>::deserialize(state, &mut rkyv::Infallible).unwrap();
```

(I don't recommend leaving this call as UFCS for ergonomics reasons)

**Comment by billyb2** [comment]
> let state = <ArchivedGameState as Deserialize<GameState, Infallible>>::deserialize(state, &mut rkyv::Infallible).unwrap();

Yep, it looks like that's the case:

```
error[E0277]: the trait bound `rkyv::Infallible: SharedDeserializeRegistry` is not satisfied
   --> src/main.rs:118:25
    |
117 | ...   <ArchivedGameState as Deserialize<GameState, rkyv::Infallible>>::deserialize(
    |       ---------------------------------------------------------------------------- required by a bound introduced by this call
118 | ...       state,
    |           ^^^^^ the trait `SharedDeserializeRegistry` is not implemented for `rkyv::Infallible`
    |
    = help: the trait `SharedDeserializeRegistry` is implemented for `SharedDeserializeMap`
    = note: required for `ArchivedRc<u8, rkyv::impls::alloc::rc::ArcFlavor>` to implement `Deserialize<Arc<AtomicU8>, rkyv::Infallible>`
    = note: 4 redundant requirements hidden
    = note: required for `ArchivedGameState` to implement `Deserialize<GameState, rkyv::Infallible>`
```
Though I'm not entirely understanding what I'm missing to fullfil that bound

**Comment by djkoloski** [comment]
Serializers that support shared pointer deserialization implement `SharedDeserializeRegistry`. Try passing [`&mut SharedDeserializeMap::new()`](https://docs.rs/rkyv/latest/rkyv/de/deserializers/struct.SharedDeserializeMap.html) instead of `&mut Infallible`.

This is just some extra deserializer state to track shared pointers and deduplicate them on the way back out of the serialized format.

**Comment by billyb2** [comment]
that seems to have worked, thank you so much!!
