### ISSUE TITLE
Question: is it possible to know the length of the serialize result before doing serialization?

### ISSUE THREAD

**Issue by al8n** [rkyv/rkyv#415]
Hi, is it possible to know the length of the serialized result before doing serialization? It is helpful to avoid reallocating multiple times when serializing.

e.g.

```rust
#[derive(Archive, Serialize, Deserialize)]
struct Foo {
  f1: Vec<u8>,
  f2: u16
}

let foo = Foo::new();
let len = foo.serialized_len();
let buf = Vec::with_capacity(len);
let ret = rkyv::ser::serializers::WriteSerializer::new(buf);
ret.serialize_value(&foo).unwrap();
```

**Comment by djkoloski** [comment]
In general, it is not possible to know the serialized length without actually performing serialization. This is because of two primary factors:

1. Packing objects with different alignments into the same buffer results in padding between them, and the amount of padding depends on the serialization order. Serialization order can very easily change with field reordering, collection ordering, etc.
2. The amount of data serialized depends on the amount of data in collections. If you serialize a `Vec<Vec<Vec<Vec<Vec<u8>>>>>`, you'd have to traverse every level of `Vec` and add up the leaf `Vec<u8>` lengths. That's a lot of work!

That said, you can precalculate the amount of space required by serializing with a "dummy serializer". This is a `Serializer` implementation that ignores the bytes it's given to write. Instead, it just keeps track of padding and the number of bytes written so far. At the end of serialization, no bytes have been written but you know how much space is required. Then you can allocate once and perform a second "real" serialization.

**Comment by al8n** [comment]
Thank you very much!
