### ISSUE TITLE
Why can't I serialize a `Vec<>` with `BufferSerializer`?

### ISSUE THREAD

**Issue by simgt** [rkyv/rkyv#423]
Hi,

I want to serialize a `Vec` (or slice) in a pre-allocated buffer, but it seems that `BufferSerializer<AlignedBytes>` doesn't satisfy `ScratchSpace`. Why?

I'm not relying on `AlignedBytes` for my specific use case, but the error is identical.

```rust
        use rkyv::{
            ser::serializers::AllocSerializer,
            ser::{serializers::BufferSerializer, Serializer},
            AlignedBytes,
        };

        let values = vec![0, 1, 2, 3];
        let mut serializer = AllocSerializer::<4096>::default();
        let pos = serializer
            .serialize_value(&values)
            .expect("failed to archive object");
        assert_eq!(pos, 0);

        let mut serializer = BufferSerializer::new(AlignedBytes([0; 4096]));
        let pos = serializer
            .serialize_value(&values)
            .expect("failed to archive object");
        assert_eq!(pos, 0);
```

The code above produces the following error:

```
error[E0277]: the trait bound `BufferSerializer<AlignedBytes<4096>>: ScratchSpace` is not satisfied
153 |             .serialize_value(&values)
    |              --------------- ^^^^^^^ the trait `ScratchSpace` is not implemented for `BufferSerializer<AlignedBytes<4096>>`
    |              |
    |              required by a bound introduced by this call
    |
    = help: the following other types implement trait `ScratchSpace`:
              HeapScratch<N>
              AllocScratch
              BufferScratch<T>
              FallbackScratch<M, F>
              ScratchTracker<T>
              CompositeSerializer<S, C, H>
    = note: required for `Vec<{integer}>` to implement `Serialize<BufferSerializer<AlignedBytes<4096>>>`
note: required by a bound in `serialize_value`
    |
77  |     fn serialize_value<T: Serialize<Self>>(&mut self, value: &T) -> Result<usize, Self::Error> {
    |                           ^^^^^^^^^^^^^^^ required by this bound in `Serializer::serialize_value`

```

_Thanks for this very nice library! 😊_

**Comment by simgt** [comment]
Turns out the answer is in [the book](https://rkyv.org/architecture/serialize.html?highlight=scratch#serializer):

> More complex types like Box and String require a serializer that implements [Serializer](https://docs.rs/rkyv/0.7.1/rkyv/ser/trait.Serializer.html), and even more complex types like Rc and Vec require a serializer that additionally implement [SharedSerializeRegistry](https://docs.rs/rkyv/0.7.1/rkyv/ser/trait.SharedSerializeRegistry.html) or [ScratchSpace](https://docs.rs/rkyv/0.7.1/rkyv/ser/trait.ScratchSpace.html).

Solution is to build a `CompositeSerializer`, I went with this as a first step:

```rust
CompositeSerializer::new(
    BufferSerializer::new(buffer_ref.map_writable().unwrap()),
    AllocScratch::default(),
    SharedSerializeMap::default(),
);
```

**Comment by MaxOhn** [comment]
You could leave some space at the front of the buffer and after serializing your data you serialize the position at the front.

```rs
let my_struct: MyStruct = ...;
let mut buffer = vec![0; 1024];

let offset = std::cmp::max(
    std::mem::size_of::<Archived<usize>>(), // needs to have enough space for the archived usize
    std::mem::align_of::<Archived<MyStruct>>(), // but must also be properly aligned
);

let mut serializer = CompositeSerializer::new(
    BufferSerializer::new(&mut buffer[offset..]), // <-
    AllocScratch::new(),
    Infallible, // PS: if you don't need the shared registry you can use Infallible here
);

let pos = serializer.serialize_value(&my_struct).unwrap();

let mut serializer = BufferSerializer::new(&mut buffer[..offset]);
serializer.serialize_value(&pos).unwrap();


let pos = rkyv::check_archived_value::<usize>(&buffer, 0).unwrap();
let archived = rkyv::check_archived_value::<MyStruct>(&buffer[offset..], *pos as usize).unwrap();
```

**Comment by simgt** [comment]
Thanks @MaxOhn!
I'm not sure I really love the idea of having to deal with an extra level of indirection to reach my structure, but I guess that works.

From the doc on `archived_root`:
> The root of the object must be stored at the end of the slice **(this is the default behavior)**

kind of suggests that another behaviour was envisioned at some point?

>     Infallible, // PS: if you don't need the shared registry you can use Infallible here

What does this do? Documentation is a bit lacking on that front.

**Comment by MaxOhn** [comment]
> What does this do? Documentation is a bit lacking on that front.

The only mandatory requirement for each for the three `CompositeSerializer` components is to be [`Fallible`].

Additionally, depending on what you want to use the serializer for, you can make it implement
- [`Serializer`] if the first component implements `Serializer`
- [`ScratchSpace`] if the second component implements `ScratchSpace`
- [`SharedSerializeRegistry`] if the third component implements `SharedSerializeRegistry`

`Serializer` and `ScratchSpace` are generally required to serialize types like `Vec<T>`, `HashMap<K, V>`, `Box<[T]>`, ...
`SharedSerializeRegistry` is generally required to serialize types like `Rc<T>`, `Arc<T>`, ...

[`Infallible`] implements neither of these but does implement `Fallible` so if you don't need them for your serializer you can use `Infallible` instead of something that implements the traits.

If you don't want to bother customizing a serializer, [`AllocSerializer`] is a type alias for a `CompositeSerializer` that you can use for pretty much anything as long as you can make allocations.

[`Fallible`]: https://docs.rs/rkyv/latest/rkyv/trait.Fallible.html
[`Serializer`]: https://docs.rs/rkyv/latest/rkyv/ser/trait.Serializer.html
[`ScratchSpace`]: https://docs.rs/rkyv/latest/rkyv/ser/trait.ScratchSpace.html
[`SharedSerializeRegistry`]: https://docs.rs/rkyv/latest/rkyv/ser/trait.SharedSerializeRegistry.html
[`Infallible`]: https://docs.rs/rkyv/latest/rkyv/struct.Infallible.html
[`AllocSerializer`]: https://docs.rs/rkyv/latest/rkyv/ser/serializers/type.AllocSerializer.html

**Comment by simgt** [comment]
Wow, thank you so much @MaxOhn, it's crystal clear and very helpful. You should consider putting this on the [`serializers`](https://docs.rs/rkyv/latest/rkyv/ser/serializers/index.html) page. 🙂
