### ISSUE TITLE
Gate PartialEq and PartialOrd impls from local to foreign types behind `extra_traits`

### ISSUE THREAD

**Issue by oeb25** [rkyv/rkyv#434]
As discovered in https://github.com/scylladb/scylla-rust-driver/pull/838, having `rkyv` in the compiled dependency tree caused the following code to not compile anymore:
```rs
extern crate rkyv;
fn test() {
  Some("") == Some(&"");
}
```
Producing the following error:
```rs
  --> src/lib.rs:3:14
   |
16 |     Some("") == Some(&"");
   |              ^^ no implementation for `Option<&str> == Option<&&str>`
   |
   = help: the trait `PartialEq<Option<&&str>>` is not implemented for `Option<&str>`
   = help: the following other types implement trait `PartialEq<Rhs>`:
             <Option<T> as PartialEq>
             <Option<U> as PartialEq<ArchivedOption<T>>>
```

By minimizing `rkyv` I managed to reduce it to this: ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d82e564231efa8bdb1c3d359df55b9ef))
```rs
struct ArchivedOption<T>(T);

impl<T: PartialEq<U>, U> PartialEq<ArchivedOption<T>> for Option<U> {
    fn eq(&self, _: &ArchivedOption<T>) -> bool {
        todo!()
    }
}

fn test() {
    Some("") == Some(&"");
}
```

Which corresponds to the following part of the rkyv. Removing this `impl PartialEq` alone removes the error.
https://github.com/rkyv/rkyv/blob/d592789c7a21570455682c095486916a6e7b61a8/rkyv/src/option.rs#L212-L217

I have created [this repo](https://github.com/oeb25/rkyv-partial-eq-error-reproduction) which reproduces the error.

**Comment by djkoloski** [comment]
That’s surprising. I’m predisposed to saying that this is a Rust issue, but I can investigate some more before sending this upstream.

**Comment by oeb25** [comment]
Yes I agree that this seems like some sort of trait resolution issue.

I'll leave a minimal reproduction here as well: ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9a3cfc2279467aa2959f9daacf8983cb))

```rs
struct Wrap<T>(T);

impl<T: PartialEq> PartialEq<Wrap<T>> for Option<T> {
    fn eq(&self, _: &Wrap<T>) -> bool {
        true
    }
}

fn test() {
    Some(()) == Some(&());
}
```

**Comment by djkoloski** [comment]
It looks like the minimal reproduction needs to specifically compare an `Option<&T>` with an `Option<&&T>`. Since `""` is an `&str` it can hide the additional reference.

**Comment by oeb25** [comment]
It seems to work with `Option<()>` and `Option<&()>` as well actually! This example here: https://github.com/rkyv/rkyv/issues/434#issuecomment-1766190754.

**Comment by Lorak-mmk** [comment]
> It seems to work with `Option<()>` and `Option<&()>` as well actually! This example here: [#434 (comment)](https://github.com/rkyv/rkyv/issues/434#issuecomment-1766190754).

Does it? I can't compile it even when I comment out the `Wrap` and `impl` parts.

**Comment by oeb25** [comment]
My mistake, you are completely right!

I've attempted to reduce it to an example that does not depend on any built in types (other than `()`): ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9540a1168f029d6f011f9d953a901f85))

```rs
struct A<T>(T);
struct B<T>(T);

trait X<T=Self> {
    fn f(&self, _: &T) {}
}

impl<T> X for A<T> {}
impl<T> X<B<T>> for A<T> {}

fn test() {
    A(&()).f(&A(&&()));
}
```

**Comment by djkoloski** [comment]
After some additional investigation, it looks like this is an unfortunate side-effect of the included impl. However, it should also be relatively rare. The compiler is attempting to unify the left- and right-hand sides of the `==` together. In doing so, it can apply deref coercion if the two types don't unify. Because they don't unify, it derefs the `Some` call on the right side and actually calls `Some(*&"")` to get an `Option<&str>` on both sides.

The compiler can only drive unification like this forward if only one applicable impl is in scope. Normally, this is the case. However, because rkyv adds impls there are suddenly multiple impls in scope. This really _shouldn't_ prevent the compiler from driving unification forward, but it's a reasonable heuristic to avoid checking every single impl.

Either way, this really isn't rkyv's fault. Maybe this is worth reporting upstream as undesirable behavior? It's also not clear to me what the implications of this are on semver compatibility (if any).

**Comment by Lorak-mmk** [comment]
Was this ever reported to Rust? If not, I can try to do it.

**Comment by djkoloski** [comment]
Nope, I don't think this has been reported upstream.

**Comment by djkoloski** [comment]
Problem impls placed behind the `extra_traits` feature in 8c1a8865337689a817da321b04e45b672560d797.
