### ISSUE TITLE
ETA for new release?

### ISSUE THREAD

**Issue by jqnatividad** [rkyv/rkyv#443]
Hi @djkoloski ,
First off, thanks for this valuable library!

Just wondering if you have an ETA for the next release since there have been a lot of changes since 0.7.42.

https://github.com/rkyv/rkyv/compare/v0.7.42...master

**Comment by djkoloski** [comment]
Thanks for asking. I have been focusing most of my efforts on getting 0.8 out the door, which will include all of the current unreleased changes as well as a number of new and improved features. I give development updates in one of our discord channels if you're interested in following development.

I see [ten commits](https://github.com/rkyv/rkyv/commits/0.7) backported to the 0.7 branch that haven't been released yet. Are there any that aren't there that you need in a new release? I haven't been very disciplined with backporting changes and maintaining separate 0.7 and 0.8 development branches.

**Comment by monoid** [comment]
@djkoloski thank you for backporting my and other changes to 0.7.  I was about to ask you to do it :)
I'm not the original poster, but for me the new 0.7 release made in a week or two would be very useful.

**Comment by Palkovsky** [comment]
@djkoloski Are you planning to backport hasbrown update to 0.7 (https://github.com/rkyv/rkyv/commit/2316d0290e1ad7d622f25501a001e0752e2fe4c2)? This would be very useful for me.

**Comment by djkoloski** [comment]
Unfortunately I can't backport hashbrown to a 0.7 release because updating the version of a supported dependency is a semver breaking change. 0.8 will be updated to the latest hashbrown, and in the future I'll probably add minor version numbers in feature names (e.g. `hashbrown-0.13`) so that multiple versions can be supported within the same rkyv minor version.

A new version of 0.7 has been released as 0.7.43.
