### ISSUE TITLE
Run test suite with `-Zrandomize-layout`

### ISSUE THREAD

**Issue by djkoloski** [rkyv/rkyv#456]
User reported inconsistent layouts even with `strict` on. We should be able to detect this with two builds (clean between) and specifying `-Zrandomize-layout`, and writing the output to disk in between. Maybe there's also a way to just dump the type layouts to a file and diff them between two runs? That might be a little easier.

**Comment by Nemo157** [comment]
The specific issue I ran into was

```
thread 'main' panicked at utils/src/ipc.rs:384:50:
called `Result::unwrap()` on an `Err` value: CheckBytesError(InvalidTuple { variant_name: "Info", inner: TupleStructCheckError { field_index: 0, inner: ContextError(ArchiveError(Unaligned { ptr: 0x55ab62d0f341, align: 4 })) } })
```

With an [`enum` where the first field of the variant is `Box<[_]>`](https://github.com/Nemo157/swww/blob/less-ub/utils/src/ipc.rs#L361). My guess was this is because `RelPtr` is not `#[repr(C)]` so the `raw_ptr` and `metadata` fields are getting swapped.

To try and force different randomizations you'll need to use `-Zlayout-seed` too, that should mean explicit cleaning isn't necessary.

**Comment by djkoloski** [comment]
Partially mitigated by the addition of the `Portable` marker trait.

**Comment by djkoloski** [comment]
4d069f9a1e8a079c19d528df125bdb49c0d48cc4 adds a test suite which uses `-Zrandomize-layout` with three separate seeds.
