### ISSUE TITLE
ETA for next release?

### ISSUE THREAD

**Issue by jqnatividad** [rkyv/rkyv#458]
Thanks again for this valuable library!

However, in my project, rkyv is the only library still using hashbrown 0.12.

The hashbrown dependency has been updated since the last release, and it'd be great if a new 0.7.x release can be published on the road to 0.8.0 😉

**Comment by djkoloski** [comment]
Unfortunately rkyv publicly supports hashbrown 0.12 specifically by providing `Archive`/`Serialize`/`Deserialize` impls for its types when the `hashbrown` feature is enabled. Since it's not a totally-internal dependency, updating it is a breaking change. Hashbrown has already been updated to 0.14 in the main branch (0.8) but we can't update it in 0.7.

**Comment by praveenperera** [comment]
Hey what about an ETA for releasing 0.8 to crates?

**Comment by djkoloski** [comment]
Development is moving steadily, but 0.8 probably won't be ready for release soon. In the past I've been overly optimistic on how soon it will be done and blown past the projections I gave. For now, I just have to keep making progress over time. I do post regular development updates in the #development discord channel if you are interested in following progress on 0.8. Sorry I can't give a more helpful answer!

**Comment by praveenperera** [comment]
No worries I was just curious, appreciate the update and the library. I’ll join the discord. Thanks!

**Comment by kornelski** [comment]
Currently ahash 0.7 is broken on nightlies, which means that hashbrown 0.12 is also broken: 

https://github.com/tkaitchuck/aHash/issues/200

**Comment by matthiasgoergens** [comment]
@djkoloski Could you give an order of magnitude estimate, please?  Do we expect `0.8` to be released in a matter of week, months or years?

**Comment by djkoloski** [comment]
> Do we expect `0.8` to be released in a matter of weeks, months or years?

Yes.

More seriously, probably months. There is a lot of work left to be done. PRs are always welcome, though I admit I don't have a lot of time to spend so I try to spend most of it writing code rather than doing project management. If you or anyone else is interested in contributing, then the discord is a good place to talk (not required, feel free to also just PR).

**Comment by djkoloski** [comment]
Update: I'm doing my best to get 0.8 out before or during RustConf next month.

**Comment by djkoloski** [comment]
The first release candidate for 0.8 has been released as `0.8.0-rc.1`. We're down to the final week prior to release.

**Comment by djkoloski** [comment]
0.8 is out now.
