### ISSUE TITLE
Syncing a DAG by exchanging deltas

### ISSUE THREAD

**Issue by andrewzhurov** [rkyv/rkyv#493]
Say, Alice and Bob work on the same DAG, accreting it with nodes.
![image](https://github.com/rkyv/rkyv/assets/13056889/ab2a732c-439d-4c2e-935b-d85273144cbf)

How could, say, Alice sync her DAG with Bob, by sending deltas she made, in rkyv?
So Bob's run-time has her node.
![image](https://github.com/rkyv/rkyv/assets/13056889/77b82e0d-27e8-4447-86f1-67e7c1250be3)

Alice could archive the whole DAG she has and send it over, but it gets ever-more costly as it grows and more nodes become known by the receiver.
Perhaps we'd want to send deltas.

My initial thoughts on it:
1. To send, package archive of deltas, nodes that are known by receiver are not included in the archive (let's call them [stem](https://www.britannica.com/topic/graft)s).
    Delta nodes that reference stems are serialized to contain their hashes instead. Let's call them scions.
2. To receive, graft scions onto stems, replacing stems's hashes with exact stem structs. I hope you like the horticulture terminology. (:

It'd be nice to be zero-copy. Bob receives an archive - he grafts nodes and is done.
But then we'd have a bunch of archives around. And nodes from one archive would need to ref to nodes in other archives. I'm not sure if it's possible. Given it is, is it simple, efficient?

Then a bit more nuance comes into play. Alice only knows what nodes Bob have for sure. But there may be more common nodes than she knows about. So she would send them too, accidentaly. Well, no prob, she couldn't have known better. Not worrying about bandwidth here, but I'm rather wary that Bob will receive that archive (it's usable, more is better than less :smile: ), but he'll be stuck with duplicate values. Even though he could graft onto one of the duplicated nodes and ignore the others altogether - the duplicates are stuck in their archive, consuming memory.

I guess having one archive for the DAG would be ideal. But that would require an archive:
- to allow selecting a subset of it (deltas to be sent)
- to be able to integrate received deltas, serving as a kind of normalized db

Is this something rkyv is suitable for?
(and maybe this is a naive approach of syncing DAGs, please let me know if there's a better way)

@djkoloski, thank you for your effort in making rkyv! It's strive towards ergonomics and zero-copy is neat.
Would be nice one day to have data sharing as easy as giving another machine a borrow.
Looking to learn what [rel](https://github.com/rkyv/rel) is meant to be.

**Comment by djkoloski** [comment]
The scheme you're describing here is a peer-to-peer replication system. If you don't have an authority which can unilaterally accept and reject modifications (i.e. a "server") then it's much more difficult to reconcile changes that happen on different clients. For example, what if Alice and Bob simultaneously perform operations that independently preserve the DAG structure, but when taken together create a cycle? For example, with two nodes A and B, if Alice adds the edge A->B at the same time that Bob adds the edge B->A, this would create a cycle and violate the DAG property. In order to avoid cases like these, the allowed operations on the DAG must be restricted so that they are infallible (e.g. "the only allowed operation is creating a new node that points to other nodes").

However, while this is an interesting problem, I think this is outside of the scope of rkyv. rkyv is purely concerned with serialization (i.e. the wire format) and this is definitely a protocol-level problem. That is to say, this problem is really about how actors communicate and remain in sync. If you just want to use rkyv as a serialization format, then it should be sufficient for encoding deltas and such. However, I don't think a more advanced use of rkyv is likely to help solve this problem. With that in mind, I'm going to close this issue.

P.S. Thanks for taking a look at rel, it's far from finished though. I am currently focusing on getting rkyv 0.8 out the door before resuming development on rel.

**Comment by andrewzhurov** [comment]
Wow, that's been a blazing fast reply! Ty for your thoughts.

Good point that the question is largely protocol-based.
Let me focus on more rkyv-specific bits. And if you think it's outside-of-scope of rkyv, please feel free to leave it unanswered.

To give a brief background on the protocol first, in case it's of help, the DAG is a Hashgraph, meaning nodes refer to other nodes by hashes. Each node has an author and signature. So we can rest assured that there won't be cycles and it's authentic.
The structure of the DAG represents history of communication between users. [Here](https://andrewzhurov.github.io/hashgraph/) I tried to explain its workings. But surely feel free to skip it.

The rkyv-related bits I'm puzzled with are:
1. Given processes need to communicate deltas, how to be waste-free (normalize/integrate received deltas)?
    E.g., when Bob receives an archive with deltas, he integrates it atop his nodes, duplicated nodes are normalized.
    I suspect rkyv's With can be used to patch received scions, substituting their hashes with exact node structs. But that requires to deserialize, AFAIK, and so I'm curious whether it's possible without.
    An alternative seems to be for a user to keep one DAGArchive and merge into it received deltas, a kind of `localDagArchive.merge(deltasArchive)`. Is it possible in rkyv? Efficient?
    Given it is,
2. Is there a way to select a subset of Archive? (deltas to be sent)
