### ISSUE TITLE
COnvert AlignedVec to vec without copy?

### ISSUE THREAD

**Issue by XavDesbordes** [rkyv/rkyv#499]
Hi,

Using Dioxus I want to send the result of the serialization over the network without copying a second time to a Vec<u8> beforehands.

The issue for the codec I opened can be [found here](https://github.com/leptos-rs/leptos/issues/2573).

`to_vec()` will reallocate. Unsafe casting didn't make it either. A Box will reallocate as well.

What are my options on the Rkyv side ?

**Comment by XavDesbordes** [comment]
Forget that, not necessary, I don't need that.
Sorry guys

**Comment by XavDesbordes** [comment]
I reopen this as multiple tests showed that it ends being necessary.

So, what is the best way to convert an `AlignedVec` to a `Vec<u8>`, without reallocating ?

**Comment by djkoloski** [comment]
You can't and should serialize directly into a `Vec<u8>` instead. `AlignedVec` allocates its memory with a alignment 16 and `Vec` assumes its storage is always allocated with the alignment of the contained type. When `Vec<u8>` gets dropped, it will free its memory assuming its layout has alignment 1, when it was actually allocated with alignment 16. This is unsound, and so the memory has to be reallocated.

If the global allocator is smart/permissive enough, then we might be able to improve the performance of `AlignedVec` -> `Vec<u8>` conversion by calling `realloc` instead of copying the data. In the worst case `realloc` will copy the data, but most allocators will not force a copy just to lower the alignment.

In 0.8 (main branch), you can serialize directly into a `Vec<u8>` with:
```rust
let bytes = rkyv::to_bytes_in::<_, Panic>(&value, Vec::new()).unwrap();
```
where `Panic` is the desired error type from `rancor`.

In 0.7 it's still possible but more annoying:
```rust
let value = "hello world".to_string();

let mut serializer = CompositeSerializer::new(
    WriteSerializer::new(Vec::new()),
    // or whatever your scratch space and shared serialize registries are
    FallbackScratch::<HeapScratch<1024>, AllocScratch>::default(),
    SharedSerializeMap::new(),
);
serializer.serialize_value(&value).unwrap();
let bytes = serializer.into_serializer().into_inner();
```

**Comment by djkoloski** [comment]
Looks like rust's `realloc` function doesn't support changing the alignment, only the size. So there's no more efficient way to do this conversion.

**Comment by XavDesbordes** [comment]
Thanks a lot, I will make it work that way
